---
title: "3rd_down"
output: html_document
date: '2022-06-29'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(nflfastR)
library(nflreadr)
library(tidyverse)
library(ggimage)
library(ggrepel)
#library(nflplotR)

options(scipen = 999)

```

```{r data and cleaning}
pbp <- load_pbp(2028:2022)

pbp <- pbp[!is.na(pbp$yards_gained), ]
pbp <- pbp[!is.na(pbp$down), ]

runpass <- pbp %>% filter(play_type == "run" | play_type == "pass")

remove(pbp)

runpass <- runpass %>% filter(fumble_lost == 0)
runpass$passer_player_name[runpass$passer_player_name == "Jos.Allen"] <- "J.Allen" #geting names right
runpass$passer_player_name[runpass$passer_player_name == "Aa.Rodgers"] <- "A.Rodgers"
runpass$passer_player_name[runpass$passer_player_name ==  "G.Minshew II"] <- "G.Minshew"  


ave_run <- runpass %>% group_by(posteam, down) %>% 
  filter(play_type == "run") %>% 
  summarise(averun = mean(yards_gained, na.rm = TRUE),
            n_run = n()) %>% 
  ungroup()

ave_pass <- runpass %>% group_by(posteam, down) %>% 
  filter(play_type == "pass") %>% 
  summarise(avepass = mean(yards_gained, na.rm = TRUE),
            n_pass = n()) %>% 
  ungroup()

avs <- left_join(ave_pass, ave_run, by = c("posteam", "down"))

avs <- left_join(avs, teams_colors_logos, by = c("posteam" = "team_abbr") )







```

graphs

```{r graphs}
library(hrbrthemes) #gives lots of font error/warnings

runpass %>% filter(play_type == "run") %>% 
  ggplot(aes(x = yards_gained, y = down, group = down)) + 
  geom_boxplot() #boxplot of runs by downs

runpass %>% filter(play_type == "pass") %>% 
  ggplot(aes(x = yards_gained, y = as.factor(down))) + 
  geom_boxplot() +
  stat_summary(fun = "mean", geom="point", color = "red") +
  labs(title = "Ave Passing Yards by Down") #boxplot of runs by downs


avs %>% ggplot(aes(x = averun, y = avepass, shape = as.factor(down), color = as.factor(down))) +
  geom_point() + theme_light() #dotplot, shape and color by down



avs %>% ggplot(aes(x = averun, y = avepass)) +
  geom_image(aes(image = team_logo_wikipedia), size = 0.05) +
  geom_abline(slope = 2, intercept = 0) +
  facet_wrap(~ down)

avs %>% ggplot(aes(x = averun, y = avepass)) +
  geom_image(aes(image = team_logo_wikipedia), size = 0.05) +
  geom_abline(slope = 2, intercept = 0) +
  facet_wrap(~ down)

runpass %>% filter(down == 3) %>% 
  ggplot(aes(yards_gained, group = play_type, color = play_type)) +
  geom_boxplot() + facet_wrap(~ series_success)
```

```{r summary stats}
runpass %>% group_by(play_type) %>% summarise(mean = mean(yards_gained), n = n()) #ave yds gained by play type

#not including 4th down
runpass %>% filter(down <= 3) %>% 
  group_by(play_type) %>% 
  summarise(mean = mean(yards_gained), n = n()) 


#epa by play type
eparp <- runpass %>% 
  group_by(play_type, down) %>% 
  summarise(mean_epa = mean(epa, na.rm = TRUE), 
            success = mean(series_success, na.rm = TRUE), 
            meanyds = mean(yards_gained, na.rm = TRUE),
            meantogo = mean(ydstogo, na.rm = TRUE),
            n = n()) %>% 
  ungroup()

eparp


#qbs on 3rd down passing - do this for other downs, and join
qbs_3rd <- runpass %>% 
  group_by(passer_player_name, posteam) %>% 
  filter(down == 3 & passer_player_name != "NA") %>% 
  summarise(mean_epa = mean(epa, na.rm = TRUE),
            mean_ydstogo = mean(ydstogo, na.rm = TRUE),
            mean_ydsgain = mean(yards_gained, na.rm = TRUE),
            n = n(),
            down = 3
            ) %>% 
  filter(n > 300) %>%
  ungroup()

qbs_3rd <- qbs_3rd %>% left_join(teams_colors_logos, by = c("posteam" = "team_abbr"))

#vert and horiz lines at league average - wish there was a way to code this into the command
qbs_3rd %>% ggplot(aes(x = mean_ydstogo3, y = mean_epa3)) +
  geom_image(aes(image = team_logo_wikipedia), size = 0.07 ) +
  geom_hline(yintercept = -0.0420, color = "red", linetype = "dashed", alpha=0.5) +
  geom_vline(xintercept = 7.67, color = "red", linetype = "dashed", alpha=0.5) +
  labs(x = "Average Yards to Go",
       y = "Average EPA, Passing",
       title = "QB Performance on 3rd Down Passes",
       subtitle = "2028 - 2022, min 300 plays",
       caption = "@jmeerse   data: nflfastR") +
  geom_label(x = qbs_3rd$mean_ydstogo[20] + .2, 
             y = qbs_3rd$mean_epa[20],
             size = 2.5,
             label = qbs_3rd$passer_player_name[20],
             )



qbs <- rbind(qbs_1rd, qbs_2rd, qbs_3rd)
qbs <- qbs[complete.cases(qbs), ]

qbs <- qbs %>% group_by(passer_player_name) %>% filter(n() == 3) %>% ungroup()

qbs <- arrange(qbs, -desc(passer_player_name))

qbs <- qbs %>% left_join(teams_colors_logos, by = c("posteam" = "team_abbr"))

qbs %>% ggplot(aes(x = mean_ydstogo, 
                   y = mean_epa, 
                   group = passer_player_name)) +
  geom_image(aes(image = team_logo_wikipedia), 
             size = 0.07 ) + 
  geom_line()


#multiple graphs
tmp <- qbs %>%
  mutate(Player2=passer_player_name)
#epa by player by down
epas <- tmp %>% 
  ggplot( aes(x=mean_ydstogo, 
              y=mean_epa)
          ) +
  geom_line( data=tmp %>% 
               dplyr::select(-passer_player_name),
             aes(group=Player2), 
             color="grey", 
             size=0.5, 
             alpha=0.5) +
  geom_line( aes(color = passer_player_name), 
             color = tmp$team_color, 
             size=1 ) +
  geom_hline(yintercept = sum(qbs$mean_epa * qbs$n) / sum(qbs$n), 
             color = "red", 
             linetype = "dashed", 
             alpha=0.5) +
  geom_vline(xintercept = sum(qbs$mean_ydstogo * qbs$n) / sum(qbs$n), 
             color = "red", 
             linetype = "dashed", 
             alpha=0.5) +
  geom_image(aes(image = team_logo_wikipedia), 
             size = 0.1  ) +
  facet_wrap(~passer_player_name) +
  labs(title = "QB Average EPA by Down and Yds to Go",
       subtitle = "3rd down on left, 1st down on right",
       caption = "@jmeerse   data: nflfastR")

epas #graph of mean epa by each down and yds to go


#columns of epa - why doesn't JAllen have 3rd down? bc it's .002

qbcol <- qbs %>% ggplot(aes(x = mean_epa, 
                   y = reorder(passer_player_name, 
                               mean_epa, sum),
                   fill = as.factor(down),
                   
                   ), 
                   group = passer_player_name) +
  geom_col()


qbcol

```

```{r success rate}
home_team <- runpass %>% filter(home_team == posteam)
away_team <- runpass %>% filter(away_team == posteam)

htsr <- home_team %>% group_by(game_id, home_team, season) %>% 
  summarise(success_rateh = mean(series_success),
            win = if ((sum(result) > 0) )
            {1}
            else
            {0}
              ) %>% 
  ungroup()

atsr <- away_team %>% group_by(game_id, away_team) %>% 
  summarise(success_ratea = mean(series_success),
            win = if ((sum(result) < 0) )
            {1}
            else
            {0}
              ) %>% 
  ungroup()

ssr <- left_join(htsr, atsr, by = "game_id")

ssr <- runpass %>% 
  group_by(game_id, home_team, posteam, season) %>% 
  summarise(
    success_rate = mean(series_success),
    win = if ((sum(result) > 0) )
            {"home win"}
            else
            {"away win"}
              ) %>% 
  ungroup()

away <- runpass %>% 
  group_by(game_id, away_team, posteam) %>%
  summarise(success_rate = mean(series_success)) %>% 
  ungroup()

ssr <- ssr %>% left_join(away, by = c("game_id", "posteam"))

ssr <- subset(ssr, select = -c(success_rate.y))

winner <- runpass %>% 
  group_by(game_id) %>% 
  summarise(tot = sum(result),
    winner = if ((tot > 0) )
            {home_team}
            else
            {away_team}
              ) %>% 
  ungroup()

ssr <- ssr %>% left_join(winner, by = c("game_id"))
```

